//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoonRunner.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThuTheoNgay
    {
        public Nullable<int> Ngay { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> TongSoLuongBan { get; set; }
        public Nullable<int> TongDoanhThu { get; set; }
        public Nullable<int> LoiNhuan { get; set; }
    }
}
